#! /bin/sh

sxhkd &
setroot $HOME/Downloads/second-cup-casual-sex.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

polybar example

bspc config border_width         4
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating

